module.exports = {
	mysqlEndpoint: 'GET_FROM_RDS_DASHBOARD_OR_MRMUSTACHOS',
	rdsUser: 'GET_FROM_RDS_DASHBOARD_OR_MRMUSTACHOS',
	rdsPort: 'GET_FROM_RDS_DASHBOARD_OR_MRMUSTACHOS',
	rdsPassword: 'GET_FROM_RDS_DASHBOARD_OR_MRMUSTACHOS',
	rdsName: 'GET_FROM_RDS_DASHBOARD_OR_MRMUSTACHOS'
};